name: flutter_app_doctruyen
description: "Ứng dụng đọc truyện - Bài tập lớn môn Lập trình Mobile"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.2
  
  # State Management
  provider: ^6.1.5
  
  # Local Database
  sqflite: ^2.4.2
  path: ^1.9.1
  
  # Local Storage
  shared_preferences: ^2.3.5
  
  # Utilities
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - .env
